apps:
  production: myron-marston
  staging: myron-marston-staging

stacks:
  all: bamboo-mri-1.9.2

config:
  all:
    BUNDLE_WITHOUT: "test:development:os_x"

collaborators:
  all:
    - "myron.marston@gmail.com"

domains:
  production:
    - "myronmars.to"

addons:
  production:
    - custom_domains:basic
